spring:
  application:
    name: Scrum Board

  datasource:
    url: jdbc:mysql://localhost:3306/scrum?useUnicode=true&characterEncoding=UTF-8
    username: scrum
    password: scrum
    driverClassName: com.mysql.jdbc.Driver
    platform: mysql

    max-idle: 50
    suspect-timeout: 60
    time-between-eviction-runs-millis: 30000

    test-on-borrow: true
    test-while-idle: true
    validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

app:
  frontendUrl: http://localhost:8080